### ISSUE TITLE
vs complied issue

### ISSUE THREAD

**Issue by liquidzym** [CLOUDS-Interactive-Documentary/CLOUDS#40] opened 2015-01-15 14:56 UTC
sorry to open up issue here,does vs version really complied? i download the feature-64bit version,but seems missing some files,etc..
i'll add details here tomorrow,
cheers

alex

**Comment by obviousjim** [comment] 2015-03-21 20:54
duplicate of issue #41

**Closed by obviousjim** 2015-03-21 20:54 UTC
